

call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
call plug#end()
				
set termguicolors
set relativenumber
set modelines=1
set tabstop=4
set expandtab
set shiftwidth=4

syntax on

colorscheme catppuccin_mocha


